import {
  Award,
  Bell,
  BookOpen,
  Bolt,
  Building2,
  Bus,
  Droplets,
  Factory,
  Flame,
  GraduationCap,
  HeartPulse,
  Home,
  Leaf,
  Lightbulb,
  Plane,
  Road,
  Rocket,
  Scale,
  Ship,
  ShieldCheck,
  ShoppingBag,
  Sun,
  Truck,
  Users,
  Utensils,
  Wheat,
  Wind,
  Zap,
  Globe,
  MapPin,
  Anchor,
  type LucideIcon,
} from "lucide-react";

/**
 * A API devolve nomes de ícone como string (HomeStat.icon,
 * InvestorOpportunity.icon, ...). Mapeamos os comuns e caímos para
 * Building2 — sem crash nem ícone partido.
 */
const MAP: Record<string, LucideIcon> = {
  award: Award,
  bell: Bell,
  book: BookOpen,
  "book-open": BookOpen,
  building: Building2,
  building2: Building2,
  bus: Bus,
  "bolt-lightning": Bolt,
  drop: Droplets,
  drops: Droplets,
  droplets: Droplets,
  water: Droplets,
  factory: Factory,
  industry: Factory,
  flame: Flame,
  energy: Zap,
  graduation: GraduationCap,
  "graduation-cap": GraduationCap,
  education: GraduationCap,
  school: GraduationCap,
  health: HeartPulse,
  "heart-pulse": HeartPulse,
  hospital: HeartPulse,
  home: Home,
  house: Home,
  leaf: Leaf,
  environment: Leaf,
  lightbulb: Lightbulb,
  plane: Plane,
  airport: Plane,
  road: Road,
  "road-2": Road,
  roads: Road,
  Estradas: Road,
  rocket: Rocket,
  scale: Scale,
  justice: Scale,
  ship: Ship,
  port: Ship,
  shield: ShieldCheck,
  "shield-check": ShieldCheck,
  transparency: ShieldCheck,
  shopping: ShoppingBag,
  market: ShoppingBag,
  commerce: ShoppingBag,
  sun: Sun,
  solar: Sun,
  truck: Truck,
  logistics: Truck,
  users: Users,
  population: Users,
  community: Users,
  agriculture: Wheat,
  agro: Wheat,
  wheat: Wheat,
  wind: Wind,
  zap: Zap,
  globe: Globe,
  map: MapPin,
  "map-pin": MapPin,
  anchor: Anchor,
  tourism: Leaf,
  palmtree: Leaf,
  palm: Leaf,
  Habitação: Home,
  Saúde: HeartPulse,
  Educação: GraduationCap,
  Águas: Droplets,
  Energia: Zap,
  Saneamento: Droplets,
};

/** Componente de ícone para nomes vindos da API. */
export function ApiIcon({ name, size = 24, className }: { name: string | null | undefined; size?: number; className?: string }) {
  const Icon = apiIcon(name);
  return <Icon size={size} className={className} aria-hidden="true" />;
}

export function apiIcon(name: string | null | undefined): LucideIcon {
  if (!name) return Building2;
  const key = name.trim().toLowerCase().replace(/\s+/g, "-");
  return MAP[name.trim()] ?? MAP[key] ?? Building2;
}
